language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.29.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl


 
install: 
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker login -u rbenkhadem -p RUHzjE776hTERns
  - docker build -f udagram-api-feed/Dockerfile -t  rbenkhadem/udagram-api-feed:latest udagram-feed-api
  - docker build -f udagram-api-user/Dockerfile -t  rbenkhadem/udagram-api-user:latest udagram-user-api
  - docker build -f udagram-frontend/Dockerfile -t  rbenkhadem/udagram-frontend:latest udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t  rbenkhadem/udagram-reverseproxy:latest udagram-reverse-proxy